#ifndef GEOGRAM_BASIC_VERSION
#define GEOGRAM_BASIC_VERSION

#define VORPALINE_VERSION_MAJOR "1"
#define VORPALINE_VERSION_MINOR "6"
#define VORPALINE_VERSION_PATCH "5"
#define VORPALINE_VERSION "1.6.5"
#define VORPALINE_BUILD_NUMBER ""
#define VORPALINE_BUILD_DATE "Fri Jun 22 14:55:41 CEST 2018"
#define VORPALINE_SVN_REVISION "????"

#endif
